name: 'Gitbook Action Build'
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout action
      uses: actions/checkout@v2
    - name: Gitbook Action
      uses: ZanderZhao/gitbook-action@v1.2.4
      with:                                   #    or fork this repo and use YourName/gitbook-action@master
        token: ${{ secrets.GITBOOK }}  # -> remember add this in settings/secrets as following